#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ovs
Version  : 2.10.0
Release  : 11
URL      : https://files.pythonhosted.org/packages/97/33/c4b889693cec4c4487ce4d4c7fc5dafeabfed7c5bbcd4a54152657a54d01/ovs-2.10.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/97/33/c4b889693cec4c4487ce4d4c7fc5dafeabfed7c5bbcd4a54152657a54d01/ovs-2.10.0.tar.gz
Summary  : Open vSwitch library
Group    : Development/Tools
License  : Apache-2.0
Requires: ovs-python3
Requires: ovs-python
Requires: sortedcontainers
BuildRequires : buildreq-distutils3
BuildRequires : openvswitch-dev
BuildRequires : sortedcontainers

%description
Python library for working with Open vSwitch

%package python
Summary: python components for the ovs package.
Group: Default
Requires: ovs-python3 = %{version}-%{release}

%description python
python components for the ovs package.


%package python3
Summary: python3 components for the ovs package.
Group: Default
Requires: python3-core

%description python3
python3 components for the ovs package.


%prep
%setup -q -n ovs-2.10.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1539049778
python3 setup.py build

%install
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
