#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ovs
Version  : 2.5.0
Release  : 4
URL      : https://pypi.python.org/packages/source/o/ovs/ovs-2.5.0.tar.gz
Source0  : https://pypi.python.org/packages/source/o/ovs/ovs-2.5.0.tar.gz
Summary  : Open vSwitch library
Group    : Development/Tools
License  : Apache-2.0
Requires: ovs-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : setuptools

%description
Python library for working with Open vSwitch

%package python
Summary: python components for the ovs package.
Group: Default

%description python
python components for the ovs package.


%prep
%setup -q -n ovs-2.5.0

%build
python2 setup.py build -b py2

%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
